def newApp
node {
  checkout scm
  stage('Building test image') {
    newApp = docker.build("poisdeux/pong:latest-test", "jenkins/test")
  }
  stage('Test image') {
    checkout([$class: 'GitSCM', branches: [[name: '*/jenkins']],
     userRemoteConfigs: [[url:   
         'https://github.com/poisdeux/pong.git']]])
    sh '''
        ls -l
    '''
  }
  stage('Push image') {
    newApp.push()
  }
}
