def newApp
node {
  checkout scm
  stage('Building test image') {
    newApp = docker.build("poisdeux/pong:latest-test", "jenkins/test")
  }
  stage('Testing test image') {
    checkout([$class: 'GitSCM', branches: [[name: '*/jenkins']],
     userRemoteConfigs: [[url:   
         'https://github.com/poisdeux/pong.git']]])
    sh '''
        make
    '''
  }
  stage('Publish test image') {
    newApp.push()
  }

  stage('Building production image') {
    newApp = docker.build("poisdeux/pong:latest-prod", "jenkins/prod")
  }
  stage('Testing production image') {
    checkout([$class: 'GitSCM', branches: [[name: '*/jenkins']],
     userRemoteConfigs: [[url:   
         'https://github.com/poisdeux/pong.git']]])
    sh '''
        make
    '''
  }
  stage('Publish production image') {
    newApp.push()
  }

}
