pipeline {
    agent none
    stages {
        stage('Building test image') {
            agent {
                dockerfile {
                    dir "jenkins/test"
                }
            }       
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/jenkins']],
                    userRemoteConfigs: [[url: 'https://github.com/poisdeux/pong.git']]])
                sh '''
                    ls -l
                    make
                '''
            }
        }
    }
}
