pipeline {
  agent { 
    dockerfile {
	dir 'jenkins/deploy'
	args '-u root:root'
    }
  }
  stages {
    stage('Copy artifacts from test') {
        steps {
            step([$class: 'CopyArtifact', filter: 'pong-1.1', fingerprintArtifacts: true, projectName: 'Pong-test', selector: [$class: 'StatusBuildSelector', stable: false]])
            sh '''
                mv pong-1.1 /usr/bin/pong
                ls -l /usr/bin/pong
            '''
        }
    }
  }
}
