pipeline {
  agent { 
    dockerfile {
	dir 'jenkins/deploy'
	args '-u root:root'
    }
  }
  stages {
    stage('Copy artifacts from test') {
        steps {
            sh '''
                echo Copying
            '''
        }
    }
  }
}
