pipeline {
  agent { 
    dockerfile {
	dir 'jenkins/deploy'
	args '-u root:root'
    }
  }
  stages {
    stage('Copy artifacts from test') {
        step([$class: 'CopyArtifact', filter: 'pong-1.1', fingerprintArtifacts: true, projectName: 'Pong-test', selector: [$class: 'StatusBuildSelector', stable: false], target: '/usr/bin/'])
        steps {
            sh '''
                ls -l ./pong-1.1
            '''
        }
    }
  }
}
