pipeline {
  agent { 
    dockerfile {
	dir 'jenkins'
	additionalBuildArgs '-t pong'
    }
  }
  stages {
    stage('build') {
        steps {
            sh '''
		make
            '''
        }
    }
    stage('Setup X window system testing tools') {
        steps {
            sh '''
                for PKG in xdotool xvfb
                    if ! dpkg -s ${PKG} > /dev/null
                    then
                        apt-get install ${PKG}
                    fi
                done
            '''
        }
    }
    stage('test') {
        steps {
            sh '''
                echo Testing
            '''
        }
    }
  }
}
