pipeline {
  agent { 
    dockerfile {
	dir 'jenkins'
	additionalBuildArgs '-t pong'
    }
  }
  stages {
    stage('build') {
        steps {
            sh '''
		make
            '''
        }
    }
  }
}
