pipeline {
  agent { 
    dockerfile {
	dir 'jenkins'
	args '-u root:root'
    }
  }
  stages {
    stage('build') {
        steps {
            sh '''
		make
            '''
        }
    }
    stage('Setup X window system testing tools') {
        steps {
            sh '''
                for PKG in xdotool xvfb
                do
                    if ! dpkg -s ${PKG} > /dev/null 2>&1
                    then
                        apt-get install -y ${PKG}
                    fi
                done
            '''
        }
    }
    stage('Test if pong starts') {
        steps {
            sh '''
                Xvfb :0 &
                ./pong-1.1 &
                PID=$!
                if ps ${PID} > /dev/null 2>&1
                then
                    sleep 1
                    kill ${PID}
                else
                    exit 1
                fi
            '''
        }
    }
    stage('Run unit tests') {
        steps {
            sh '''
                echo Unit testing
            '''
        }
    }
    stage('Run integration tests') {
        steps {
            sh '''
                echo Unit testing
            '''
        }

    }
    stage('Run acceptance tests') {
        steps {
            sh '''
                echo Unit testing
            '''
        }

    }
  }
}
